"""first migration

Revision ID: 9e1a972496b8
Revises: 
Create Date: 2026-03-10 00:01:35.551199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1a972496b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Booking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Booking_end_at'), 'Booking', ['end_at'], unique=False)
    op.create_index(op.f('ix_Booking_id'), 'Booking', ['id'], unique=False)
    op.create_index(op.f('ix_Booking_room_id'), 'Booking', ['room_id'], unique=False)
    op.create_index(op.f('ix_Booking_start_at'), 'Booking', ['start_at'], unique=False)
    op.create_table('OutboxEvent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('BOOKING_CREATED', 'BOOKING_UPDATED', 'BOOKING_CANCELED', name='outboxeventtype'), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='outboxstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OutboxEvent_id'), 'OutboxEvent', ['id'], unique=False)
    op.create_table('Room',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Room_id'), 'Room', ['id'], unique=False)
    op.create_index(op.f('ix_Room_name'), 'Room', ['name'], unique=True)
    op.create_table('User',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_name'), 'User', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_name'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Room_name'), table_name='Room')
    op.drop_index(op.f('ix_Room_id'), table_name='Room')
    op.drop_table('Room')
    op.drop_index(op.f('ix_OutboxEvent_id'), table_name='OutboxEvent')
    op.drop_table('OutboxEvent')
    op.drop_index(op.f('ix_Booking_start_at'), table_name='Booking')
    op.drop_index(op.f('ix_Booking_room_id'), table_name='Booking')
    op.drop_index(op.f('ix_Booking_id'), table_name='Booking')
    op.drop_index(op.f('ix_Booking_end_at'), table_name='Booking')
    op.drop_table('Booking')
    # ### end Alembic commands ###
